import { useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, Crown, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { TextField } from '@/components/ui/TextField';
import { FormError } from './FormError';
import { claimOwnership } from '@/lib/server';
import { ApiError } from '@/lib/api';

/**
 * Turns possession of the server's ownership key into the right to create its
 * first account.
 *
 * The key is generated by the setup script and lives in the server's .env. It
 * proves the person at this screen is the operator, not merely someone who
 * found the address — which is the whole difference on a server exposed to the
 * internet before anyone has signed up.
 *
 * The key is not spent here. The ticket this returns is spent when the owner
 * account is actually created, so a failed signup does not strand the server
 * with a key that no longer works.
 */
export function ClaimOwnershipForm({
  serverName,
  onClaimed,
  onBack,
}: {
  serverName: string;
  onClaimed: (claimTicket: string) => void;
  onBack: () => void;
}) {
  const [key, setKey] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError(null);
    try {
      const { claim_ticket } = await claimOwnership(key.trim());
      onClaimed(claim_ticket);
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.message
          : 'Could not reach the server. Check that it is still running.',
      );
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="auth-card alloy-panel">
      <div className="mb-5 flex flex-col gap-2">
        <button
          onClick={onBack}
          className="no-drag mb-2 inline-flex w-fit items-center gap-2 text-xs transition-transform hover:-translate-x-0.5"
          style={{ color: 'var(--color-fg-muted)' }}
        >
          <ArrowLeft className="h-3.5 w-3.5" /> Choose a different server
        </button>

        <span className="telemetry-label" style={{ color: 'var(--color-accent)' }}>
          Step two
        </span>
        <h2 className="font-display text-2xl font-semibold tracking-[-0.03em]">
          Claim {serverName}
        </h2>
        <p className="max-w-md text-sm leading-6" style={{ color: 'var(--color-fg-muted)' }}>
          Nobody owns this server yet. Enter the ownership key your setup script printed and you
          become its owner. It is used once and then stops working, so no one else can take it
          afterwards.
        </p>
      </div>

      <form onSubmit={submit} className="flex flex-col gap-3">
        <TextField
          label="Ownership key"
          placeholder="Paste the key from your server's .env"
          autoFocus
          spellCheck={false}
          autoCapitalize="off"
          autoCorrect="off"
          value={key}
          onChange={(e) => setKey(e.target.value)}
          icon={<Crown className="h-4 w-4" />}
          hint="Printed by ./setup.sh, and stored as OWNERSHIP_KEY in your server's .env file."
        />

        {error && <FormError message={error} />}

        <Button
          type="submit"
          disabled={busy || key.trim().length === 0}
          icon={busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <ArrowRight className="h-4 w-4" />}
        >
          {busy ? 'Verifying…' : 'Claim this server'}
        </Button>
      </form>
    </div>
  );
}
